version = 0.1

[default.global.parameters]
stack_name = "unplugd"
resolve_s3 = true
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Environment=dev"

[dev.deploy.parameters]
stack_name = "unplugd-dev"
parameter_overrides = "Environment=dev"
confirm_changeset = false

[prod.deploy.parameters]
stack_name = "unplugd-prod"
parameter_overrides = "Environment=prod"
confirm_changeset = true
